#!/usr/bin/env python3
"""
BPMN Visualizer CLI Tool
"""
import sys
import os

# Add current directory to path so we can import our modules
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from bpmn_visualizer import main

if __name__ == '__main__':
    sys.exit(main())
